INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (1, 'go');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (1, 'will go');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (1, 'went');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (1, 'goes');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (2, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (2, 'have been');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (2, 'were');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (2, 'will be');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (3, 'England');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (3, 'Australia');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (3, 'Singapore');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (3, 'France');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (4, 'off');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (4, 'up');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (4, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (4, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (18, 'thirsty');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (18, 'hungry');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (18, 'empty');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (18, 'nothing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (19, 'any');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (19, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (19, 'some');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (19, 'nothing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (20, 'swims');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (20, 'swimming');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (20, 'swim');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (20, 'nothing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (21, 'to');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (21, 'at');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (21, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (21, 'nothing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (22, 'cold');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (22, 'hot');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (22, 'cool');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (22, 'warm');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (23, 'them');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (23, 'theirs');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (23, 'their');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (23, 'nothing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (24, 'listens');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (24, 'reads');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (24, 'watches');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (24, 'say');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (25, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (25, 'much');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (25, 'old');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (25, 'sometimes');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (26, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (26, 'much');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (26, 'often');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (26, 'sometimes');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (27, 'What');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (27, 'Which');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (27, 'How');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (27, 'When');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (42, 'will');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (42, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (42, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (42, 'won''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (43, 'become');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (43, 'became');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (43, 'becomes');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (43, 'will become');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (44, 'Some');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (44, 'Many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (44, 'Few');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (44, 'A lot');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (45, 'pollute');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (45, 'polluted');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (45, 'pollution');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (45, 'polluting');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (46, 'go');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (46, 'say');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (46, 'know');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (46, 'to');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (47, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (47, 'an');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (47, 'two');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (47, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (48, 'my');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (48, 'my''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (48, 'me');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (48, 'I');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (49, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (49, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (49, 'am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (49, 'am''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (50, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (50, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (50, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (50, 'an');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (51, 'Woker');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (51, 'doctor');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (51, 'farmer');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (51, 'student');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (52, 'very');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (52, 'much');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (52, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (52, 'old');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (53, 'at');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (53, 'under');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (53, 'up');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (53, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (54, 'by');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (54, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (54, 'of');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (54, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (55, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (55, 'an');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (55, 'a''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (55, 'an''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (56, 'am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (56, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (56, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (56, 'aren''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (57, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (57, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (57, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (57, 'isn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (58, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (58, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (58, 'of');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (58, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (59, 'my');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (59, 'my name');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (59, 'I');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (59, 'I''m');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (60, 'rides');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (60, 'riding');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (60, 'ride');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (60, 'ride''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (61, 'any');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (61, 'many''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (61, 'any''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (61, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (62, 'has');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (62, 'haven''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (62, 'have');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (62, 'hasn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (63, 'and');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (63, 'too');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (63, 'end');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (63, 'two');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (64, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (64, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (64, 'an');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (64, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (65, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (65, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (65, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (65, 'to');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (66, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (66, 'am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (66, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (66, 'isn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (67, 'board');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (67, 'boards');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (67, 'say');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (67, 'tell');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (68, 'My');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (68, 'Me');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (68, 'Am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (68, 'I''m');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (69, 'First');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (69, 'second');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (69, 'third');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (69, 'fourth');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (70, 'colours');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (70, 'colour');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (70, 'colour''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (70, 'colourn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (71, 'who');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (71, 'when');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (71, 'what');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (71, 'why');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (72, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (72, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (72, 'am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (72, 'not');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (73, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (73, 'aren''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (73, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (73, 'this');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (74, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (74, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (74, 'of');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (74, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (109, 'game');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (109, 'names');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (109, 'name');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (109, 'name''s');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (110, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (110, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (110, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (110, 'too');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (111, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (111, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (111, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (111, 'isn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (112, 'name is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (112, 'names''');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (112, 'names');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (112, 'is name');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (113, 'her');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (113, 'she');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (113, 'his');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (113, 'he');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (114, 'has');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (114, 'haven''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (114, 'hasn''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (114, 'have');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (115, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (115, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (115, 'an');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (115, 'a');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (116, 'by');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (116, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (116, 'of');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (116, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (117, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (117, 'aren''t');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (117, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (117, 'this');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (118, 'is');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (118, 'are');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (118, 'am');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (118, 'not');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (156, 'do/ do');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (156, 'are / do');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (156, 'did / do');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (156, 'are / going to do');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (157, 'Vietnamese');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (157, 'American');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (157, 'Singapore');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (157, 'Singaporean');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (158, 'didn’t/ had');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (158, 'doesn’t/ has');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (158, 'didn’t/ has');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (158, 'doesn’t/ had');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (159, 'ski');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (159, 'skiing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (159, 'to ski');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (159, 'to skiing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (160, 'How');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (160, 'What');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (160, 'Where');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (160, 'Who');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (161, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (161, 'at');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (161, 'for');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (161, 'in');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (162, 'is writeing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (162, 'is writing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (162, 'writes');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (162, 'wrote');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (163, 'to fly');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (163, 'flying');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (163, 'fly');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (163, 'to flying');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (164, 'How old');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (164, 'How');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (164, 'How far');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (164, 'How many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (165, 'season');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (165, 'seasons');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (165, 'people');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (165, 'students');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (166, 'at');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (166, 'with');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (166, 'from');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (166, 'for');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (167, 'much');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (167, 'many');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (167, 'less');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (167, 'fewer');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (168, 'play');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (168, 'plays');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (168, 'will play');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (168, 'is playing');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (169, 'How');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (169, 'What');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (169, 'When');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (169, 'Where');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (170, 'more intelligent');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (170, 'intelligent');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (170, 'most intelligent');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (170, 'less intelligent');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (171, 'teacher');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (171, 'doctor');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (171, 'farmer');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (171, 'journalist');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (172, 'How');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (172, 'What');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (172, 'When');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (172, 'Why');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (173, 'on');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (173, 'at');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (173, 'to');
INSERT INTO T_POSSIBLE_ANSWER (question_id, possible_answer_text) VALUES (173, 'in');
