server:
  servlet:
    context-path: /api
spring:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  liquibase:
    change-log: classpath:changelog/master-changelog.xml


