spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: {{JDBC_URL}}
    username: {{JDBC_USERNAME}}
    password: {{JDBC_PASSWORD}}
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
server:
  servlet:
    context-path: /api

