spring:
  datasource:
    url: jdbc:mysql://mysql/quiz_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

